# Ingeniería Informática de Gestión y Sistemas de Información
# Administración de Sistemas
# Alan García Justel
#
# Fichero de configuración de Prometheus. Prometheus es un sistema para
# monitorizar aplicaciones y definir y enviar alertas. 
# En este caso vamos a utilizarlo para registrar los datos de la base de
# datos y enviarselos a nuestro dashboard de grafana.
#

global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'web'
    static_configs:
      - targets: ['web:3000']  # Puerto de la aplicacion web